// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_CGzMuL6sDoQj-uNV5i6Kcb7OHWjsHRU',
    appId: '1:887729724859:web:4b3c94104203ed8a3cf89e',
    messagingSenderId: '887729724859',
    projectId: 'expense-tracker-bb951',
    authDomain: 'expense-tracker-bb951.firebaseapp.com',
    storageBucket: 'expense-tracker-bb951.firebasestorage.app',
    measurementId: 'G-1KQK2MEKEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAznBebh_cuxHqrDQwomXQ3ybarZVq0j5k',
    appId: '1:887729724859:android:51aa2b193587607d3cf89e',
    messagingSenderId: '887729724859',
    projectId: 'expense-tracker-bb951',
    storageBucket: 'expense-tracker-bb951.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpnS1xBJqcrK6WTp3QzizgF23M-wkd7eY',
    appId: '1:887729724859:ios:ea92fb95a14e86c83cf89e',
    messagingSenderId: '887729724859',
    projectId: 'expense-tracker-bb951',
    storageBucket: 'expense-tracker-bb951.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpnS1xBJqcrK6WTp3QzizgF23M-wkd7eY',
    appId: '1:887729724859:ios:ea92fb95a14e86c83cf89e',
    messagingSenderId: '887729724859',
    projectId: 'expense-tracker-bb951',
    storageBucket: 'expense-tracker-bb951.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_CGzMuL6sDoQj-uNV5i6Kcb7OHWjsHRU',
    appId: '1:887729724859:web:1ef298281f0ec9543cf89e',
    messagingSenderId: '887729724859',
    projectId: 'expense-tracker-bb951',
    authDomain: 'expense-tracker-bb951.firebaseapp.com',
    storageBucket: 'expense-tracker-bb951.firebasestorage.app',
    measurementId: 'G-8S14255WKN',
  );
}
